package sample.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DriverProfile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer age;
   private java.lang.String gender;
   private java.lang.String name;
   private java.lang.String state;
   private java.lang.Boolean hasPreviousIncidents;

   public DriverProfile()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Boolean getHasPreviousIncidents()
   {
      return this.hasPreviousIncidents;
   }

   public void setHasPreviousIncidents(java.lang.Boolean hasPreviousIncidents)
   {
      this.hasPreviousIncidents = hasPreviousIncidents;
   }

   public DriverProfile(java.lang.Integer age, java.lang.String gender,
         java.lang.String name, java.lang.String state,
         java.lang.Boolean hasPreviousIncidents)
   {
      this.age = age;
      this.gender = gender;
      this.name = name;
      this.state = state;
      this.hasPreviousIncidents = hasPreviousIncidents;
   }

}