package sample.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DriverProfile implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DriverProfile() {
    }

}