package sample.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PriceQuotation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer price;

   public PriceQuotation()
   {
   }

   public java.lang.Integer getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Integer price)
   {
      this.price = price;
   }

   public PriceQuotation(java.lang.Integer price)
   {
      this.price = price;
   }

}